# Generated by Django 4.2 on 2023-06-06 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_alter_autor_nombre'),
        ('genero', '0001_initial'),
        ('libro', '0006_alter_libro_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='libros', to='autor.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='libros', to='genero.genero', verbose_name='Genero'),
        ),
    ]
