# Generated by Django 4.2 on 2023-06-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
